# inb4: just_for_lulz

services:
  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: lurkmore
      POSTGRES_PASSWORD: lurkmore_pass
      POSTGRES_DB: lurkmore_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: